# Generated by Django 5.2.5 on 2025-11-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.webpage'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='topic_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.topic'),
        ),
    ]
